services:
  - type: web
    name: quiz-application
    env: docker
    region: oregon
    plan: free
    dockerContext: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: quizdb
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: quizdb
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: quizdb
          property: password
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_JPA_SHOW_SQL
        value: "false"
      - key: SPRING_THYMELEAF_CACHE
        value: "true"
      - key: SERVER_PORT
        value: 10000
      - key: LOG_LEVEL
        value: INFO
databases:
  - name: quizdb
    databaseName: quizdb
    plan: free
